Feature/hw3
KipDurron/GBShop pull request #4
Opened 2021-06-26 17:15 UTC by KipDurron

was added new functions for products and makes unit tests

2021-06-28 10:16 UTC, DrBoat requested changes
Оставил несколько комментарием, исправь их пожалуйста до 8 июля

2021-06-28 10:16 UTC, DrBoat commented on GBShopTests/ProductTests.swift
> +                XCTFail()
Добавь вывод ошибки (error)

2021-06-28 10:16 UTC, DrBoat commented on GBShopTests/ProductTests.swift
> +                XCTFail()
И здесь

2021-06-28 10:16 UTC, DrBoat commented on GBShopTests/LoginTests.swift
> +                XCTFail()
Тут вывод ошибки

2021-06-28 10:16 UTC, DrBoat commented on GBShopTests/LoginTests.swift
> +                self.expectation.fulfill()
Тут можно в `debugPrint` вывести `login`

2021-06-28 15:29 UTC, KipDurron commented on GBShopTests/ProductTests.swift
> +                XCTFail()
done

2021-06-28 15:29 UTC, KipDurron commented on GBShopTests/ProductTests.swift
> +                XCTFail()
done

2021-06-28 15:30 UTC, KipDurron commented on GBShopTests/LoginTests.swift
> +                XCTFail()
done

2021-06-28 15:30 UTC, KipDurron commented on GBShopTests/LoginTests.swift
> +                self.expectation.fulfill()
done

2021-06-28 18:56 UTC, DrBoat commented on GBShopTests/LoginTests.swift
> +                XCTFail()
`error.localizedDescription`

 И ее можно передать аргументом к XCFail()

2021-06-29 19:24 UTC, KipDurron commented on GBShopTests/LoginTests.swift
> +                XCTFail()
исправил

2021-07-01 20:01 UTC, DrBoat approved these changes
Теперь топ, можно вливать!

2021-07-02 06:11 UTC, merged